# Core Colors
background            #13140d
foreground            #e4e3d7
selection_foreground  #bfce7f
selection_background  #2b3400
cursor                #bfce7f
cursor_text_color     #13140d

# Regular Colors
color0  #13140d
color1  #ffb4ab
color2  #bfce7f
color3  #a1d0c4
color4  #dbea98
color5  #e1e6c3
color6  #c5c9a8
color7  #e4e3d7

# Bright Colors
color8  #393a31
color9  #ffb4ab
color10 #bfce7f
color11 #a1d0c4
color12 #dbea98
color13 #e1e6c3 
color14 #c5c9a8
color15 #e4e3d7
