[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.cursor]
text = '#131313'
cursor = '#e2e2e2'

[colors.vi_mode_cursor]
text = '#131313'
cursor = '#4dd8e7'

[colors.search.matches]
foreground = '#474747'
background = '#b8c6ea'

[colors.search.focused_match]
foreground = '#474747'
background = '#4dd8e7'

[colors.footer_bar]
foreground = '#474747'
background = '#e2e2e2'

[colors.hints.start]
foreground = '#474747'
background = '#b1cbcf'

[colors.hints.end]
foreground = '#474747'
background = '#b1cbcf'

[colors.selection]
text = '#c6c6c6'
background = '#474747'


[colors.normal]
black   = '#474747'
red     = '#ffb4ab'
green   = '#4dd8e7'
yellow  = '#b1cbcf'
blue    = '#b8c6ea'
magenta = '#4dd8e7'
cyan    = '#b1cbcf'
white   = '#e2e2e2'


[colors.bright]
black   = '#919191'
red     = '#ffb4ab'
green   = '#4dd8e7'
yellow  = '#b1cbcf'
blue    = '#b8c6ea'
magenta = '#4dd8e7'
cyan    = '#b1cbcf'
white   = '#e2e2e2'


[colors.dim]
black   = '#474747'
red     = '#ffb4ab'
green   = '#4dd8e7'
yellow  = '#b1cbcf'
blue    = '#b8c6ea'
magenta = '#4dd8e7'
cyan    = '#b1cbcf'
white   = '#e2e2e2'
