font_family JetBrainsMono Nerd Font
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

symbol_map U+1F300-U+1FAFF Noto Color Emoji
symbol_map U+2600-U+26FF Noto Color Emoji


background_opacity 0.7
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

allow_remote_control yes
allow_remote_control socket-only
listen_on unix:/tmp/kitty

include ~/.config/kitty/colors.conf
