color0 #474747
color1 #ffb4ab
color2 #4dd8e7
color3 #b1cbcf
color4 #b8c6ea
color5 #4dd8e7
color6 #b1cbcf
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #4dd8e7
color11 #b1cbcf
color12 #b8c6ea
color13 #4dd8e7
color14 #b1cbcf
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #4dd8e7
inactive_border_color #474747
url_color             #4dd8e7

active_tab_foreground   #00363b
active_tab_background   #4dd8e7
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
